### ISSUE TITLE
Option to exclude save code

### ISSUE THREAD

**Issue by Kroc** [cadaver/c64loader#1]
Thank you so much for your loader! I was writing a diskmag a few years ago (https://github.com/Kroc/nucomer) and getting loading and music working together was too difficult for me to do, even Krill's loader stumped me. I've just gone back to this problem and have been able to integrate your loader with ease.

Since I'm writing a diskmag outfit, my requirements are a little different from a game. I have written a bootstrap that consists of just the fastloader code and a call to load the next PRG file; this is so that the minimal number of bytes needs to be loaded via KERNAL's slow load. This bootstrap is 2'279 bytes but I exomize it to reduce that to 2'103 bytes. This is still a little large and I'd like to cut it down more.

I won't, at least at yet, need any save functionality; could you add an option, via a symbol, to exclude all save functionality to cut the binary size down a bit more?

Kind regards,
Kroc Camen

**Comment by cadaver** [comment]
Check the v3 branch now. It doesn't cut down size that much though. I changed the SD2IEC path blindly, will verify later.

**Comment by Kroc** [comment]
Appreciated all the same, thank you! I'm having some trouble getting the exomizer loading to work, but I'll try and narrow this down first

**Comment by Kroc** [comment]
I've got a encoding/decoding problem: we can see the decompressed code goes awry after `lda # %00000111`

![image](https://user-images.githubusercontent.com/142650/228217087-4632d580-dfa0-4291-8535-a79240bee7a7.png)

Maybe this is because I'm using Exomizer v3.1? I used the encoding parameters from your makefile in my batch file:
(the `,2` here skips the 2-byte PRG header)

```bat
%EXOMIZER% ^
     raw -T4 -M256 -c ^
     -o "build\logo.exo" ^
     -- "build\logo.prg",2
```

**Comment by Kroc** [comment]
Sorry, I fixed it easily! You need to add `-P-32` to the exomizer command to turn off the new bit 5 in the encoding parameters: 

![image](https://user-images.githubusercontent.com/142650/228219012-701fa20f-087f-4768-823a-0b71fb2f1846.png)

**Comment by cadaver** [comment]
Yes, Exomizer has progressed too rapidly :) When in doubt, you can always drop in your own Exomizer decompressor code, as the loader is modular.

**Comment by cadaver** [comment]
Tested also on SD2IEC. Should be fine now.

**Comment by Kroc** [comment]
Don't you also need to exclude the save code parts that are uploaded to the drive or is this already done?

**Comment by cadaver** [comment]
Right, good point :) That should further reduce the size. Just have to see that it's safe. Some of the code (handling a command) is shared.

**Comment by cadaver** [comment]
Now should be done. There is further possibility for hand-reducing the footprint, but it would mean changing the protocol and drivecode init, which would in turn make the code harder to maintain.

**Comment by Kroc** [comment]
Not worth the effort, I may yet need save again in the distant future.

--edit: You should add `-P-32` to your Makefile exomizer params so that the output is compatible when using latest Exomizer!

**Comment by cadaver** [comment]
It is already there in the current v3 branch when making the example datafile.
